version: "3.8"
services:
  sentiment-api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./models:/app/models
    restart: unless-stopped
    environment:
      - PORT=3000
      - HOST=0.0.0.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
